## 作业

### 容错

> 既然index是非精确匹配，接口也没有写错。为什么要全部渲染为err？理想的效果是：Index正常显示，User报错的内容单独显示。是否存在解决方法？

以下是我的解决方案：

留意到在store/user.js下`getUserInfo `，单独捕获axios错误后，页面不再报错。因此考虑在catch中返回错误信息：

```js
// 异步的dispatchAction
export const getUserInfo = server => {
 return (dispatch, getState, axiosInstance) => {
     // 返回promise
     return axios.get('http://localhost:9001/user/info1').then((res) => {
         const { info } = res.data;
         console.log('info', info);
         dispatch(getInfo(info));
     }).catch(e=>{
         // 容错
         return dispatch(getInfo({
             errMsg:e.message
         }));
     })
 }
}
```

然后在组件中增加容错选项，以user为例：

```react
function User(props){
 // 容错处理
 if(props.info.errMsg){
     return <h1>{props.info.errMsg}</h1>
 }
 
 useEffect(()=>{
     if(!props.info.name){
         props.getUserInfo();
     }
 },[]);
 const {name,honor}=props.info;
 return <div>
     <h1>你好，{name}，你当前的成就是：
     <span style={{textDecoration:'underline'}}>{honor}</span>
     </h1>
 </div>
}
```

实现效果如下：

![](http://markdown.djtao.net/FgH9iAuohDrCJpXgP-UU11S6Kyu2)

所有组件对loadData处理后，不再需要在PromiseAll中处理。

**复用处理**：

- 考虑到catch中逻辑一致，可以用一个通用方法统一封装返回的报错内容使之健壮。

```JS
// ...
.catch(err=>{
handleErr(err);
})
```

- 留意到所有组件都在一开始前判断，考虑用一个高阶组件封装原来的所有组件。j简易代码如下：

```react
function Wrap(props,component){
if(props.errMsg){
 return <Error errMsg={props.errMsg} />
}
return component
}
```

实现从略。

### 跨域

>  如何不再单独启mock.js服务？

考虑反向代理，单独定义api路由下的接口统一转发到另外一个端口。